### ISSUE TITLE
Histograms does not display properly?

### ISSUE THREAD

**Issue by mxlei01** [lanpa/tensorboard-pytorch#101]
I think there might be something wrong with bins=tensorflow, I've tried two different types of bins, which is tensorflow and auto. It showed two vastly differently histograms.

Bins: tensorflow
Distribution:
![image](https://user-images.githubusercontent.com/7399324/37324036-d7741970-264c-11e8-9020-44921dd4aed6.png)

Histogram:
![image](https://user-images.githubusercontent.com/7399324/37324052-edd521fa-264c-11e8-89c6-87fed2238d7f.png)

Code:
```
# Tensorboard: Loop through weights and biases and save them in tensorboard
for name, param in rnn.named_parameters():
    writer_train.add_histogram(f"{group_name}/{name}", param, epoch)
```

Bins: auto
Distribution:
![image](https://user-images.githubusercontent.com/7399324/37324168-7b9433be-264d-11e8-8a9b-eebdf27981e7.png)

Histogram:
![image](https://user-images.githubusercontent.com/7399324/37324155-707b20dc-264d-11e8-914e-36d91c3e20ce.png)

Code:
```
# Tensorboard: Loop through weights and biases and save them in tensorboard
for name, param in rnn.named_parameters():
    writer_train.add_histogram(f"{group_name}/{name}", param, epoch, bins="auto")
```

**Comment by lanpa** [comment]
yes, that is expected. The default binning of tensorflow is weird. I am considering for another default option.
