### ISSUE TITLE
Wrong when use add_graph

### ISSUE THREAD

**Issue by LZDSJTU** [lanpa/tensorboard-pytorch#105]
Traceback (most recent call last):
  File "demo.py", line 58, in <module>
    writer.add_graph(resnet18, (dataset, ))
  File "/home/liang/tensorboard-pytorch/tensorboardX/writer.py", line 400, in add_graph
    self.file_writer.add_graph(graph(model, input_to_model, verbose))
  File "/home/liang/tensorboard-pytorch/tensorboardX/graph.py", line 51, in graph
    with torch.onnx.set_training(model, False):
AttributeError: module 'torch' has no attribute 'onnx'

**Comment by LZDSJTU** [comment]
I check that the version of my torch does not have onnx. And some answer says that I need to install pytorch by source. I want to know if there is some method simpler. I can use tensorboard except this function.

**Comment by LZDSJTU** [comment]
I check that the version of my torch does not have onnx. And some answer says that I need to install pytorch by source. I want to know if there is some method simpler. I can use tensorboard except for this function.

**Comment by lanpa** [comment]
Hi, to use `add_graph()`, upgrading to pytorch v0.3.1 should be the easiest way.
