### ISSUE TITLE
add_embedding TF dependecy

### ISSUE THREAD

**Issue by lucabergamini** [lanpa/tensorboard-pytorch#11]
Hello again,

Since add_embedding relies on TF,
```
import tensorflow as tf
```
on line 58, I get a constant stream of tensorflow GPU logging events during training about the creation of the gpu device every time the function is called. Even if if does not compromise the functionality, it makes the output log a real mess to read.

Are you planning to strip the dependency (as have already been done with the SummaryWriter object) ?

**Comment by lanpa** [comment]
Hi, if you know how to install from source, please give it a test. Thanks

**Comment by lucabergamini** [comment]
Trying now, i'll let you know how it goes :)

**Comment by lucabergamini** [comment]
It works :) built from source using the setup script and installed with pip in virtualenv. Great work :)
