### ISSUE TITLE
Problem with specifying run name

### ISSUE THREAD

**Issue by akamaus** [lanpa/tensorboard-pytorch#115]
I created the summary writer object like follows:
`self.writer = SummaryWriter('logs', self.name + '_' + datetime.now().strftime('%D-%T'))`

Scalars I render in multiple experiments end up displayed in single run named '.', so I can't distinguish between experiments. I used tensorboard packed with tensorflow-1.1 and tensorboardX-1.0

**Comment by lanpa** [comment]
http://tensorboard-pytorch.readthedocs.io/en/latest/tensorboard.html
So if you pass something to the first argument (which overrides the default), the second argument will have no effect.
For your case, you can use `SummaryWriter('logs/' + self.name + '_' + datetime.now().strftime('%D-%T'))`. And be care with the slashes or colons.

**Comment by akamaus** [comment]
oh, sorry. Should've read the docs more carefully. Works now.
