### ISSUE TITLE
log_dir and comment not working together in SummaryWriter

### ISSUE THREAD

**Issue by mlagunas** [lanpa/tensorboard-pytorch#124]
As it is in master, you cannot use a specific `log_dir` with the variable `comment`.
The current code directly creates the `file_writer` with the specified `log_dir` ignoring `comment`. 

```python
if not log_dir:
    import socket
    from datetime import datetime
    current_time = datetime.now().strftime('%b%d_%H-%M-%S')
    log_dir = os.path.join('runs', current_time + '_' + socket.gethostname() + comment)
self.file_writer = FileWriter(logdir=log_dir)
```

Seems straight forward to add `comment` even when `log_dir` is specified:

```python
if not log_dir:
    import socket
    from datetime import datetime
    current_time = datetime.now().strftime('%b%d_%H-%M-%S')
    log_dir = os.path.join('runs', current_time + '_' + socket.gethostname())
self.file_writer = FileWriter(logdir=log_dir + comment)
```

Similarly, if we want to log the date also:
```python
if not log_dir:
    log_dir = 'runs'
import socket
from datetime import datetime
current_time = datetime.now().strftime('%b%d_%H-%M-%S')
log_dir = os.path.join(log_dir, comment + current_time)
self.file_writer = FileWriter(logdir=log_dir)
```
Is this behaviour between `log_dir` and `comment` intended? Is it worth a PR?

**Comment by lanpa** [comment]
I use `time + hostname + comment` for simple logging. If users want a customized logging path (e.g. parameter, dataset, special time format ...), they should just compose their `log_dir` and ignore the `comment` argument. PRs are welcome as long as the behavior is backward compatible. (For example, your last snippet forcefully append time to the user's dir.)
