### ISSUE TITLE
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by HouseW** [lanpa/tensorboard-pytorch#126]
Hi @lanpa ,thanks for this tool.I am trying to run the comand: tensorboard --logdir , and it report the ImportError:

> ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory

i guess it is about the cuda runtime enviroment. How can i use this tool with cuda9.0?

**Comment by lanpa** [comment]
You need to install cuda9 compatible tensorflow.

**Comment by HouseW** [comment]
Thank you, it works now!
