### ISSUE TITLE
demo.py  No network structure

### ISSUE THREAD

**Issue by clwh310** [lanpa/tensorboard-pytorch#129]
Who can help me

tensorboardX       1.1 
pytorch                0.3.1 
tensorflow(cpu)            1.6      

In addition to the network structure, others are successful
![image](https://user-images.githubusercontent.com/23579782/39286267-8abda26a-494f-11e8-83ed-82d6f4a90f77.png)

**Comment by clwh310** [comment]
resnet18 = models.resnet18(Ture)

**Comment by lanpa** [comment]
Because I put add_graph demo in separate file.

**Comment by clwh310** [comment]
I know, thank you! Thank you again for writing this plugin for pytorch
