### ISSUE TITLE
Why do we need input to add_graph method

### ISSUE THREAD

**Issue by laoreja** [lanpa/tensorboard-pytorch#132]
Why there must `input_to_model` argument in the `add_graph` method?
Since usually we only want one copy of graph data, altering input usually will not alter the graph.

Do you mean I should make a dummy input and run the method only once, or should I run this method every time I feed a new batch of data to the graph? Will the latter option cause too much computation, taking too much disk space?

**Comment by lanpa** [comment]
1. Because a pytorch graph is *defined by run*. `input_to_model` is needed to trigger the forward pass.
2. `add_graph` should be executed only once. (unless your model changes every iteration). This should be used outside the training loop.
