### ISSUE TITLE
Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by pinkfloyd06** [lanpa/tensorboard-pytorch#133]
Hello,

l get the following error while l run 
`tensorboard --logdir runs`
even if tensorflow  is installed

```
anaconda3/envs/kinetics/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: dnnBatchNormalizationCreateBackward_v2_F32


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problem


Thank you for your helps

```

**Comment by lanpa** [comment]
can you `import tensorflow` without error? If failed, what is the error message?

**Comment by mazariahmed06** [comment]
yes l import tensorflow without error

**Comment by lanpa** [comment]
@mazariahmed06 @pinkfloyd06  Do you have same problem? what is the result of `pip list|grep tensor` ?

**Comment by pinkfloyd06** [comment]
pip3 list|grep tensor
tensorboardX                       1.2                 
tensorflow                         1.5.0               
tensorflow-gpu                     1.5.0               
tensorflow-tensorboard             1.5.0

**Comment by pinkfloyd06** [comment]
Problem solved after removing and reinstalling tensorflow.

Thanks
