### ISSUE TITLE
Support nested tags

### ISSUE THREAD

**Issue by nuance** [lanpa/tensorboard-pytorch#14]
From [the tensorflow docs](https://github.com/tensorflow/tensorflow/blob/r1.2/tensorflow/tensorboard/README.md#tags-giving-names-to-data), it seems like I should be able to organize data into nested groups. However, it looks like `/` is included in the `_INVALID_TAG_CHARACTERS` [regex](https://github.com/lanpa/tensorboard-pytorch/blob/master/tensorboard/summary.py#L50) so it's stripped.

The comment mentions using name scopes, but I can't figure out what that's referring to or how to use those instead.

**Comment by nuance** [comment]
Actually, this seems to work correctly (didn't see the invert on the regex char class), not sure what I was doing wrong...

**Comment by nuance** [comment]
(btw, great work on this project, it's working out great for me)

**Comment by lanpa** [comment]
`writer.add_scalar('directory/like/hierarchy1', random.random(), n_iter)`

![image](https://user-images.githubusercontent.com/2005323/29330763-db15da56-822c-11e7-8674-84295a6aff5e.png)
Seems it's not stripped.

Currently, you can only use tree depth = 1, e.g.:
`/parent/child1`
`/parent/child2`
then child1 and child2 will be grouped under parent.
