### ISSUE TITLE
Histgrams error here

### ISSUE THREAD

**Issue by jxgu1016** [lanpa/tensorboard-pytorch#142]
Relative code:
```
writer.add_histogram(name, param.clone().cpu().data.numpy(), iteration)
```
Histgrams in Tensorboard:
<img width="330" alt="2018-05-14 4 20 33" src="https://user-images.githubusercontent.com/16861577/39985954-d1f82082-5792-11e8-8e1e-0291dd55cc49.png">
All the histgrams are the same, so is this a bug?
My PyTorch version is 0.3.1 with tensorboard 1.5.1.
I installed the tensorboardX 1.2 with pip.

**Comment by leonardoaraujosantos** [comment]
Ohh man same with me here :)

**Comment by lanpa** [comment]
Have you checked #78 ?

**Comment by jxgu1016** [comment]
Works for me. Thanks a lot.

**Comment by lanpa** [comment]
@leonardoaraujosantos Because I am not sure about how dynamic histogram binning (changes every time you call `add_histogram`) might affect tensorboard plot. Will do a comprehensive survey about it in the future.
