### ISSUE TITLE
Remove progress bar and verbose output during GIF creation

### ISSUE THREAD

**Issue by mdfirman** [lanpa/tensorboard-pytorch#143]
During the creation of gifs, progress bars and other verbose output are displayed in the terminal. This will break the look of whatever else we want to print during training, typically some nice table of training progress.

This unwanted output is a product of [moviepy](https://github.com/Zulko/moviepy). I have created a moviepy [pull request](https://github.com/Zulko/moviepy/pull/799) to make this output optional. If this is merged in, then perhaps we can consider changing

    clip.write_gif(filename, verbose=True)

To

    clip.write_gif(filename, verbose=False, progress_bar=False)

 in `tensorboardX/summary.py`.

**Comment by mdfirman** [comment]
I have been thinking about how we could remain backwards compatible for people who haven't got the latest moviepy. One simple option could be:

```
try:
    clip.write_gif(filename, verbose=False, progress_bar=False)
except TypeError:
    clip.write_gif(filename, verbose=False)
```

**Comment by lanpa** [comment]
yes, please send a PR~
