### ISSUE TITLE
histogramm error

### ISSUE THREAD

**Issue by E1eMenta** [lanpa/tensorboard-pytorch#146]
pytorch 0.3.1.post2
TensorBoard 1.7.0 

Tensorbord distributions consist of one value 3e+18.
![image](https://user-images.githubusercontent.com/32593811/40495864-0777f35e-5f81-11e8-8838-43fb80e92296.png)
How can I fix it?

**Comment by lanpa** [comment]
`pip install git+https://github.com/lanpa/tensorboard-pytorch`
