### ISSUE TITLE
Restore `global_step` from logs

### ISSUE THREAD

**Issue by lcswillems** [lanpa/tensorboard-pytorch#149]
I trained my model and plotted some graphs using `add_scalar`. I saved my model but not the `global_step`. I would like to continue training, is there a way to recover `global_step`?

**Comment by lanpa** [comment]
`global_step` is maintained by the user. so I guess what you want is to append the scalars to a certain graph. It that correct?

**Comment by lcswillems** [comment]
Thank you for you answer. I just wanted to know if there is a way to recover the `global_step` from the `tfevents` file.
By the way, your code is really great!

**Comment by lanpa** [comment]
Got it, it's possible. For example, https://github.com/lanpa/tensorboard-dumper/blob/master/dump.py
The code dumps all the images in the event file. By counting the while loop, you get the `global step`. (although very inefficient) I would rather keep the step/epoch information along with optimizer's running info.
