### ISSUE TITLE
Implement support of Matplotlib figures

### ISSUE THREAD

**Issue by vojtamolda** [lanpa/tensorboard-pytorch#152]
Hello @lanpa,

First of all, thanks a lot for investing the time and developing this project. I find it super useful whenever I try (and usually fail ;) hacking _PyTorch_.

Frequently, when I work there's a need to create _Matplotlib_ plot and add it to _TensorBoard_. There are known and well documented ways to do it by converting the figure to image. One of your [examples](https://github.com/lanpa/tensorboard-pytorch/blob/master/examples/matplotlib_demo.py) in this repo actually demonstrates it and there's a [few other ways](https://github.com/wookayin/tensorflow-plot) to achieve the same result.

I was wondering if it would make sense to implement `SummaryWriter.add_figure(...)` method that would accept `matplotlib.Figure`, convert it into a RGB image and then add it to _TensorBoard_. I think the implementation could look roughly like this:

```python
import matplotlib.pyplot as plt
import matplotlib.backends.backend_agg as plt_backend_agg

class SummaryWriter:
    def add_figure(self, tag, figure, global_step=None, close_figure=True):
        canvas = plt_backend_agg.FigureCanvasAgg(figure)
        canvas.draw()
        data = np.frombuffer(canvas.buffer_rgba(), dtype=np.uint8)
        w, h = figure.canvas.get_width_height()
        image = data.reshape([h, w, 4])[:, :, 0:3]
        if close_figure:
            plt.close(figure)
        self.add_image(tag, image, global_step)

```

I'll submit a PR if you think adding the method makes sense and it fits well into the API.

Have a good one!

**Comment by lanpa** [comment]
``` python
from utils import figureToImg
def figureToImg(tag, figure, global_step=None, close_figure=True):
    canvas = plt_backend_agg.FigureCanvasAgg(figure)
    canvas.draw()
    data = np.frombuffer(canvas.buffer_rgba(), dtype=np.uint8)
    w, h = figure.canvas.get_width_height()
    image = data.reshape([h, w, 4])[:, :, 0:3]
    if close_figure:
        plt.close(figure)
    return image
writer.add_image(tag, figureToImg(figure), global_step)
```

Some quick thoughts:
1. We should make it fail fast and decouple the code if possible.
2. User can plot a batch of plots. ex: `writer.add_image(tag, torch.cat(figureToImg(figure), figureToImg(figure1), figureToImg(figure2),...))` without `subplot()`
3. It should be easier to deal with other libs such as pandas visualization in the future.
4. The result of `figureToImg(figure)` can be saved to disk easily.
5. There's an `add_video()` function, so the return value of `figureToImg()` can be used to make GIFs too.

What do you think?

**Comment by vojtamolda** [comment]
Thanks a lot for replying and your discussion ideas. Here are my thoughts:

1. The decoupling comes at a cost of extra `from tensorboardX.utils import figureToImg` line the user has to type. You're right that _matplotlib_ would become a "soft" dependency just like _moviepy_. Situation here is a bit different though. Absence of `matplotlib` on a system can't end up as a late failure since one can't create a plot without it whereas one can easily create a movie without _moviepy_.

2. I didn't know about the batch feature. I have to try it out someday... I think we can support a single figure or a list of figures: `writer.add_figure(tag, [figure1, figure2, ...])` to "mimic" this feature.

3. I agree. Maybe we can mix both ideas together by having `utils.figureToImg(...)` for conversion that would be called from `SummaryWriter.add_figure(...)`.

4. That's true that saving would be somewhat easier. But I think vast majority of people who use this library want to display the image in _TensorBoard_ so they can avoid storing it on disk.

5. There's a special API for [`matplotlib.animations`](https://matplotlib.org/api/animation_api.html) so maybe videos should be handled in a separate issue, because it may be harder to figure out the right API than it seems at the first sight.

6. Using the `tensorboardX.utils.figureToImg` has also the disadvantage of being a buried deeper in the documentation (BTW The [RTFD docs](http://tensorboard-pytorch.readthedocs.io/en/latest/index.html) are great) and harder to find for the end-user. The `figureToImg(...)` function wouldn't be directly listed on the [main page](http://tensorboard-pytorch.readthedocs.io/en/latest/tensorboard.html), right?



So I guess the choice between the two options is a matter of taste more than anything else:
- Option **A**:
   ```python
    writer.add_figure(tag, fig, global_step)
    writer.add_figure(tag, [fig1, fig2, fig3], global_step)
    ```
- Option **B**:
    ```python
    from tensorboardX.utils import figureToImg
    writer.add_image(tag, figureToImg(fig), global_step)
    writer.add_image(tag, torch.cat([figureToImg(fig1), figureToImg(fig2), figureToImg(fig3)], global_step)
    ```

**Comment by lanpa** [comment]
2. plotting a batch is simply passing [N, H, W, 3] array to `add_image()`. add_figure(tag, [figure1, figure2, ...]) looks good too.
4. For people who don't need tensorboard, they can use your code to save plot easily:)
- so your reply on point 3 serves this.
6. It can be listed under a new class tensorboardX.utils

I agree the difference is the API. And we can provide both options with the idea of point 3 :)

**Comment by vojtamolda** [comment]
Agreed. Thanks. PR coming in a little bit.

**Comment by lanpa** [comment]
thanks!
