### ISSUE TITLE
the problem about add_image

### ISSUE THREAD

**Issue by travel-go** [lanpa/tensorboard-pytorch#158]
Hello,I want to draw a attention picture,but when I use the function of add_image,I find have no image to writer.However, the function of add_scaler to be used will generate some files.

PyTorch 0.4 / torchvision 0.2 / tensorboard 1.7.0

**Comment by lanpa** [comment]
please provide more information such as a code section to reproduce it.

**Comment by ml7** [comment]
@travel-go just wanted to follow up on this, do you have steps to reproduce?

**Comment by travel-go** [comment]
Thank you for reply,I have solved this problem.
