### ISSUE TITLE
Black Images in embedding

### ISSUE THREAD

**Issue by lucabergamini** [lanpa/tensorboard-pytorch#16]
Related to #12 , some configuration still leads to black images for the first column of the sprite. It happens with sprites completely full (i.e. the number of images is a perfect square), but only with some configurations (i.e 49 does but 100 does not). The TB implementation seems a really mess IMHO, so its not excluded it is their fault somehow. 

I suggest to leave this open for other users.

**Comment by lanpa** [comment]
I also confirmed that Tensorflow's embedding output has same issue. Thanks
