### ISSUE TITLE
Gif temporary files never deleted

### ISSUE THREAD

**Issue by mdfirman** [lanpa/tensorboard-pytorch#160]
When logging gifs, the `/tmp/` folder on the computer fills up with thousands of two types of files:

Gif files like:

    /tmp/tmpa4wzio8o.gif

And folders like:

    /tmp/pymp-zmjrppci/listener-9vi9u40r

After a night's training, I ended up with 60GB of these files sat in the tmp dir!

I wonder if these are the temporary files created [here](https://github.com/lanpa/tensorboard-pytorch/blob/master/tensorboardX/summary.py#L212)? Should they be deleted at the end of `make_video`?

**Comment by lanpa** [comment]
Yes they should be removed. Is `/tmp/pymp-zmjrppci/listener-9vi9u40r` very large? This folder might be the by-product of multiprocessing. (and tensorboardX didn't use that)

**Comment by mdfirman** [comment]
Actually no, the `pymp-*` folders are tiny, and much less plentiful than the `.gif` files. So I'm happy to live with these for now! Preventing the `.gif` buildup is the most important.

(And, yes, I am writing to tensorboardX in a `Thread()` here so maybe that's where they come from)
