### ISSUE TITLE
How can I use it show feature maps?

### ISSUE THREAD

**Issue by woaichipinngguo** [lanpa/tensorboard-pytorch#168]
I  get the output of the conv1  layer which shape is [7,32,32,32]. How can I  use tensorboard  show  feature maps? Use writer.add_image? @lanpa

**Comment by lanpa** [comment]
For a feature map of size [N, C, H, W], you can resize it to [N*C, 1, H, W] and pass it to add_image().

**Comment by woaichipinngguo** [comment]
Thanks. I'll try it.
