### ISSUE TITLE
module 'google.protobuf.symbol_database' has no attribute 'Default

### ISSUE THREAD

**Issue by nikhileshva** [lanpa/tensorboard-pytorch#170]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/udd/py3env/lib/python3.5/site-packages/tensorboardX/__init__.py", line 4, in <module>
    from .writer import FileWriter, SummaryWriter
  File "/home/udd/py3env/lib/python3.5/site-packages/tensorboardX/writer.py", line 24, in <module>
    from .src import event_pb2
  File "/home/udd/py3env/lib/python3.5/site-packages/tensorboardX/src/event_pb2.py", line 13, in <module>
    _sym_db = _symbol_database.Default()
AttributeError: module 'google.protobuf.symbol_database' has no attribute 'Default'
```

I get this error when importing SummaryWriter
```
from tensorboardX import SummaryWriter
```

and I installed it through pip

```
pip install tensorboardX
```

Python Version: 3.5
pytorch version: 0.4.0

This is the output from pip freeze

numpy==1.13.3
olefile==0.44
opencv-python==3.4.1.15
parso==0.2.1
pexpect==4.6.0
pickleshare==0.7.4
Pillow==4.3.0
prompt-toolkit==1.0.15
protobuf==3.6.0
ptyprocess==0.5.2
Pygments==2.2.0
pyparsing==2.2.0
python-dateutil==2.6.1
pytz==2017.3
PyWavelets==0.5.2
PyYAML==3.12
scikit-image==0.13.1
scikit-learn==0.19.1
scipy==1.0.0
simplegeneric==0.8.1
six==1.11.0
tensorboardX==1.1
tensorflow-tensorboard==1.5.1
toolz==0.9.0
torch==0.4.0
torchvision==0.2.1
traitlets==4.3.2
wcwidth==0.1.7
Werkzeug==0.14.1

What did I miss??

**Comment by lanpa** [comment]
Hi, `pip install tensorboardX` should end up with  tensorboardX==1.2 installed. please install with `pip install git+https://github.com/lanpa/tensorboard-pytorch`

**Comment by nikhileshva** [comment]
I did that and it didn't work then too. I uninstalled protobuf and tensorflow again. It worked then. 

Thanks for response.
