### ISSUE TITLE
add_image has no effect: No images are shown on the website

### ISSUE THREAD

**Issue by linzhiqiu** [lanpa/tensorboard-pytorch#172]
This is kinda a weird issue.. But I found that the add_image() method is not working anymore.. The other functions in SummaryWriter such as add_text() still works properly. Anyone seeing such errors before? What might have happened?

I was using add_image() for a really large tensor ( like 3 x 100000 x 512 ), and that doesn't print me out any image on website. But later on when I switch it back to normal size image ( like 3 x 512 x 512 ), it is still not working.

Is it because I need to close() the SummaryWriter object?

**Comment by linzhiqiu** [comment]
Well, I figured out the issue.. You need to call() in the end, otherwise the event may not have already been logged. God I spent my day on this

**Comment by fujunustc** [comment]
What's the meaning of call() in the end?
