### ISSUE TITLE
How can I save multiple csv files quickly

### ISSUE THREAD

**Issue by raymondchua** [lanpa/tensorboard-pytorch#173]
Hi, 
If I have multiple saved variables which results in multiple plots, how can I save these multiple plots quickly in csv? Right now I am clicking them individually and this takes too much time.

**Comment by lanpa** [comment]
There is a https://github.com/lanpa/tensorboard-dumper, which dumps all images.
It should be easy to modify from this one.

**Comment by raymondchua** [comment]
@lanpa , thanks for the info. Do you know how the demo.pb is generated in the tensorboard-dumper repo?

**Comment by lanpa** [comment]
see readme :)

**Comment by raymondchua** [comment]
@lanpa, unfortunately I did not get any .pb files when I run demo.py 
Are you sure demo.py generates pb files?

**Comment by lanpa** [comment]
oh, sorry I renamed it.

The original name should looks like `events.out.tfevent...` under the `runs` directory

**Comment by raymondchua** [comment]
@lanpa , Thanks! That works. It might be useful to update the readme file at  https://github.com/lanpa/tensorboard-dumper.

**Comment by lanpa** [comment]
would you like to send a PR? XD

**Comment by raymondchua** [comment]
@lanpa , sure, I can do that! :)
