### ISSUE TITLE
add embedding with different size(0) of tensor and metadata

### ISSUE THREAD

**Issue by edchengg** [lanpa/tensorboard-pytorch#176]
Thanks for your work!
When I use the add_embedding, it requires the tensor and metadata has the same length.
However, when I have multiple columns for the metadata(muti labels), I need to have a header for the metadata(n+1 rows). Otherwise, the tensorboard raise an error saying "Multi-column metadata should have a header"..
So how should I include it in the metadata if it leads to different size(0)? Thank you!

I tried to save two metadata files with different global_step and replace the one without header with the one with header.

**Comment by lanpa** [comment]
ed1643f This commit should handle your case.
What's your tensorboardX version?

**Comment by edchengg** [comment]
Thanks!
