### ISSUE TITLE
Can you support the entire page screenshot?

### ISSUE THREAD

**Issue by acgtyrant** [lanpa/tensorboard-pytorch#18]
I tired this [捕捉网页截图 - FireShot的](https://chrome.google.com/webstore/detail/take-webpage-screenshots/mcbpblocgmgfnpjjppndjkmgjaogfceg). However, it returns:

![fireshot capture 3 - tensorboard - http___35 197 26 245_6006_ scalars](https://user-images.githubusercontent.com/3921062/29601365-c1540b1a-880d-11e7-83f1-2672441e5634.png)

It is occulated and cropped in the right.

**Comment by lanpa** [comment]
Hi, I refer you to
https://github.com/tensorflow/tensorboard
for a feature request. I don't know much about web programming.
