### ISSUE TITLE
Draw a weight change graph

### ISSUE THREAD

**Issue by travel-go** [lanpa/tensorboard-pytorch#183]
Recently,I meet a problem.I want to draw a picture about weight and loss in training,but the weight is a tensor like(50000*500).so I should draw a 3D picture.
Weight was constantly changing during training, so I picked a few epoch's weights to draw this graph. But I find that tensorboardX doesn't seem to be able to draw. I want to make sure it is or not?
I tried the add_histogram() function and the add_embedding() function, but I didn't particularly understand the meaning of these two functions.
This is  my draw‘s picture.What is the abscissa of this image?Does this peak represent the largest value?
I think the DISTRIBUTIONS should be a numerical distribution, but the HISTOGRAMS is not very understandable.
![image](https://user-images.githubusercontent.com/31921471/42146160-a0aff87e-7df8-11e8-9fd0-e9c729de124c.png)
![1530508311 1](https://user-images.githubusercontent.com/31921471/42146306-8acd6b62-7df9-11e8-9a84-64494bf6b364.png)

I think the picture I want to make should be similar to the embedding function. I want to put multiple weights into the add_embedding function. Is this okay?
At the same time, I think that what I want to draw might use matlab. Below is the picture I want to draw. Can you give me some advice?

![img_6622](https://user-images.githubusercontent.com/31921471/42146479-af4e8c68-7dfa-11e8-8714-c39b54d485bb.PNG)

I'm looking forward for your reply.Thank you.

**Comment by lanpa** [comment]
1. There was a bug related to add_histogram(). Please install from source and see if the result looks reasonable.
2. I don't think add_embedding() can do the job as you said. Please see the demo and see what add_embedding can do.

**Comment by travel-go** [comment]
Thank you for your reply.
