### ISSUE TITLE
resume logging after checkpoint 

### ISSUE THREAD

**Issue by pluiez** [lanpa/tensorboard-pytorch#187]
Hi, I'm wondering how logging records will continue after reloading a previously saved checkpoint? Will it get messy with garbage records?

**Comment by lanpa** [comment]
please see https://github.com/lanpa/tensorboard-pytorch/blob/master/examples/demo_purge.py for example. (need to install from source at this time point)

**Comment by alexcoca** [comment]
Hi @lanpa, would it be possible possible to explain this demo and how to integrate it with e.g., demo.py?
