### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by Stonesjtu** [lanpa/tensorboard-pytorch#2]
Env
---
> anaconda2
> ubuntu 14.04

error log:
```log
with open('HISTORY.rst') as history_file:
IOError: [Errno 2] No such file or directory: 'HISTORY.rst'
```

The pip repo is not updated yet. The version is **0.4**

**Comment by lanpa** [comment]
HI

Please try `pip install tensorboard-pytorch --no-cache-dir` to get newest version.

As for python2, it will be supported in next version.

**Comment by lanpa** [comment]
Just made a python2 version on PyPI and tested with travis CI. 
enjoy:)
