### ISSUE TITLE
Please add a variant of add_image which accepts PNG as file

### ISSUE THREAD

**Issue by olegtarasov** [lanpa/tensorboard-pytorch#21]
Hi! I am plotting some custom stuff with pyplot during training and want to add these plots to TensorBoard as images. Since TensorBoard uses PNG, it would be really convenient to have `add_image` which accepts a file (or BytesIO) as input. It would be mush easier to save a plot to memory in PNG format and skip all that tensor juggling.

**Comment by lanpa** [comment]
HI, The next release (tensorboardX) will also support numpy array as input. I think it's better to let user handle the image loading things. Users only need to define a function to load whatever format they want and feed the numpy array to `add_image`. As for skipping file IO, do you use method like this: https://stackoverflow.com/questions/43363388/how-to-save-a-greyscale-matplotlib-plot-to-numpy-array or are there better ways?

thanks

**Comment by gar1t** [comment]
This request might be now reconsidered in light of the `add_figure` support. There's now a pattern of providing convenience functions that rely on specialized encoding. It seems these conveniences are implemented at the SummaryWriter level, which keeps them out of the lower layers.
