### ISSUE TITLE
[Feature Request] optionally remove an experiment

### ISSUE THREAD

**Issue by chihyaoma** [lanpa/tensorboard-pytorch#23]
Hey, thanks for the great work!

It would be even better if there is an option to optionally remove a particular experiment like what we have in Crayon. 
```python
from pycrayon import CrayonClient

# Connect to the server
cc = CrayonClient(hostname="server_machine_address")
cc.remove_experiment(xp_name) # remove the 'xp_name' experiment
```

Thanks!

**Comment by lanpa** [comment]
Can that be achieved with `shutil.rmtree('xp_name')` ?
I am curious about the use case lol.

**Comment by chihyaoma** [comment]
Nope. Not really. As far as I know, TensorBoard will lock down the directory. You will have to shut down the TensorBoard and remove the directory after that. This will create problems when you have a lot of experiments host by the TensorBoard since once it's back online, it will still take time to load all the data saved before. 

For most of the time, my experiments have customized names, but there are still some cases I would like to remove a single or a few experiments that are no longer important or simply wrong. Having this feature will simplify the procedure a lot (shut down -> remove directory -> restart -> wait until it loads all previous data).

**Comment by lanpa** [comment]
Have you tried the reload button in tensorboard interface after removing the folder? My tensorboard (1.2.1) handles your situation perfectly. (both adding or removing folder)

**Comment by chihyaoma** [comment]
Sorry, there might be a misunderstanding. 

What I am trying to say is that you can't remove the folder while the TensorBoard is still running. If you shut down the TensorBoard and remove the folder, it will work. 

So, I guess the question is: can you remove the folder contains experiment event file, while your TensorBoard is still running?

I am using Tensorflow version 1.3.0 and TensorBoard version 0.1.5, by the way.

**Comment by lanpa** [comment]
HI, I can remove the folder with `rm -rf xp_name ` while tensorboard is running. Also tested on  Tensorflow version 1.3.0 and TensorBoard version 0.1.5.

**Comment by chihyaoma** [comment]
Well... I can't remove the folder. The TensorBoard locks it down. 
```
rm: cannot remove ‘experiment_name/’: Directory not empty
```

Not sure if this has anything to do with the fact that my log_dir is on NFS.

**Comment by lucabergamini** [comment]
try rm -r

**Comment by lanpa** [comment]
Did you use `-rf`?

**Comment by chihyaoma** [comment]
Yes, of course. Thank you for asking though.

**Comment by lanpa** [comment]
Then I think the python script `shutil.rmtree('xp_name')` will not work as well. btw, mine storage environment is also NFS share.

**Comment by chihyaoma** [comment]
Yeah, that was the first thing I tried, and then I realized that `rm -rf` wasn't working as well. 

I guess I will try to do some further testing. Thanks for the help!
