### ISSUE TITLE
Multiple Embeddings in One Experiment

### ISSUE THREAD

**Issue by taoari** [lanpa/tensorboard-pytorch#24]
For add_scalar, add_histogram, add_image, etc., they accept a `tag` argument to indicate different tensors. However, `add_embedding` does not have such an argument. Is it possible to add this argument so as to monitor multiple embeddings in one experiment?

**Comment by lanpa** [comment]
Yes, possible. The keypoint lies in 
https://github.com/lanpa/tensorboard-pytorch/blob/master/tensorboardX/embedding.py#L35

I will do it maybe this weekend.
