### ISSUE TITLE
TypeError: Parameter to MergeFrom() must be instance of same class: expected Summary got Summary. for field Event.summary

### ISSUE THREAD

**Issue by DavidRoboter** [lanpa/tensorboard-pytorch#25]
Hi,

I'm using pytorch on Windows10 following the tutorial in 'https://zhuanlan.zhihu.com/p/26871672'

When i try tensorboardX out, i keep getting the following error:
TypeError: Parameter to MergeFrom() must be instance of same class: expected Summary got Summary. for field Event.summary

I also tested in Ubuntu, no error occurred. So I guess it maybe caused by windows platform (or not ╮(╯▽╰)╭). Anyway, could you have a look on this issue and hopely provide a solution? After all, many guys are still bonded with Windows.

My pip freeze is listed below:

>pip freeze
alabaster==0.7.9
anaconda-clean==1.0
anaconda-client==1.5.1
anaconda-navigator==1.3.1
appdirs==1.4.3
apptools==4.4.0
argcomplete==1.0.0
astroid==1.4.7
astropy==2.0.2
autopep8==1.3.2
Babel==2.3.4
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.5.1
bitarray==0.8.1
blaze==0.10.1
bleach==1.5.0
bokeh==0.12.2
boto==2.42.0
Bottleneck==1.2.1
cffi==1.10.0
chardet==3.0.2
chest==0.2.3
click==6.6
cloudpickle==0.2.1
clyent==1.2.2
colorama==0.3.7
comtypes==1.1.2
conda==4.3.25
conda-build==2.0.2
configobj==5.0.6
contextlib2==0.5.3
cryptography==1.5
cycler==0.10.0
Cython==0.24.1
cytoolz==0.8.0
dask==0.15.2
datashape==0.5.2
decorator==4.0.10
dill==0.2.5
docutils==0.12
dynd===c328ab7
envisage==4.5.1
et-xmlfile==1.0.1
fastcache==1.0.2
filelock==2.0.6
Flask==0.11.1
Flask-Cors==2.1.2
gevent==1.1.2
greenlet==0.4.10
h5py==2.7.0
HeapDict==1.0.0
html5lib==0.9999999
idna==2.1
imagesize==0.7.1
ipykernel==4.5.0
ipython==5.1.0
ipython-genutils==0.1.0
ipywidgets==5.2.2
itsdangerous==0.24
jdcal==1.2
jedi==0.9.0
Jinja2==2.8
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.4.0
jupyter-console==5.0.0
jupyter-core==4.2.0
lazy-object-proxy==1.2.1
llvmlite==0.20.0
locket==0.2.0
lxml==3.6.4
Markdown==2.6.9
MarkupSafe==0.23
matplotlib==2.0.2
menuinst==1.4.1
mistune==0.7.3
mpmath==0.19
multipledispatch==0.4.8
nb-anacondacloud==1.2.0
nb-conda==2.0.0
nb-conda-kernels==2.0.0
nbconvert==4.2.0
nbformat==4.1.0
nbpresent==3.0.2
networkx==1.11
nltk==3.2.1
nose==1.3.7
notebook==4.2.3
numba==0.35.0
numexpr==2.6.2
numpy==1.13.1
numpydoc==0.6.0
odo==0.5.0
opencv-python==3.3.0+contrib
openpyxl==2.3.2
packaging==16.8
pandas==0.20.3
partd==0.3.6
path.py==0.0.0
pathlib2==2.1.0
patsy==0.4.1
pep8==1.7.0
pickleshare==0.7.4
Pillow==3.3.1
pkginfo==1.3.2
ply==3.9
prompt-toolkit==1.0.3
protobuf==3.4.0
psutil==4.3.1
py==1.4.31
pyasn1==0.1.9
pycodestyle==2.3.1
pycosat==0.6.1
pycparser==2.14
pycrypto==2.6.1
pycurl==7.43.0
pyface==5.1.0
pyflakes==1.3.0
Pygments==2.1.3
pylint==1.5.4
pyOpenSSL==16.2.0
pyparsing==2.2.0
pyreadline==2.1
pytest==2.9.2
python-dateutil==2.6.0
pytz==2017.2
PyWavelets==0.5.2
pywin32==220
PyYAML==3.12
pyzmq==15.4.0
QtAwesome==0.4.4
qtconsole==4.2.1
QtPy==1.1.2
requests==2.13.0
rope-py3k==0.9.4.post1
ruamel-yaml===-VERSION
scikit-image==0.13.0
scikit-learn==0.19.0
scipy==0.19.1
seaborn==0.7.1
selenium==3.4.1
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
snowballstemmer==1.2.1
sockjs-tornado==1.0.3
Sphinx==1.3.1
spyder==3.1.4
SQLAlchemy==1.0.13
statsmodels==0.8.0
svgwrite==1.1.6
sympy==1.0
tables==3.2.2
tensorboardX==0.6.9
tensorflow==1.3.0
tensorflow-tensorboard==0.1.6
toolz==0.8.0
torch==0.2.1+a4fc05a
torchvision==0.1.9
tornado==4.4.1
traitlets==4.3.0
unicodecsv==0.14.1
update==0.4.4
wcwidth==0.1.7
Werkzeug==0.12.2
widgetsnbextension==1.2.6
win-unicode-console==0.5
wrapt==1.10.6
xgboost==0.6
xlrd==1.0.0
XlsxWriter==0.9.3
xlwings==0.10.0
xlwt==1.1.2

**Comment by lolongcovas** [comment]
I got the same error in ubuntu 14.04 to plot an image. however, i didnt have error in adding scalar values.

**Comment by lanpa** [comment]
I also got this error on my mac recently... will look into it later. XD
@lolongcovas would you post your `pip freeze` as well? thanks

**Comment by micklexqg** [comment]
the same error occured at writer.add_scalar('data/scalar1', s1[0], n_iter) # data grouping by `slash`

**Comment by EntilZha** [comment]
I ran into this issue as well using code very similar to the example in the docs. The relevant pip freeze entries for me are

```
tensorflow==1.3.0
tensorflow-tensorboard==0.1.5
tensorboardX==0.6.9
```

**Comment by lanpa** [comment]
Found out that the problem happens in V0.6.9
It should work well (on windows/mac/ubuntu) if you build from source code or use the following temporary package.

[tensorboardX-0.7.5-py2.py3-none-any.whl.zip](https://github.com/lanpa/tensorboard-pytorch/files/1324271/tensorboardX-0.7.5-py2.py3-none-any.whl.zip)
