### ISSUE TITLE
[Minor] SummaryWriter.add_histogram on usage section of README does not properly work

### ISSUE THREAD

**Issue by lenscloth** [lanpa/tensorboard-pytorch#27]
One line at usage section of README does not properly work on python3.6
```python
       for name, param in resnet18.named_parameters():
            writer.add_histogram(name, param, n_iter)
```
This code produces weird looking spike like histogram 

![kazam_screenshot_00000](https://user-images.githubusercontent.com/22115436/30729869-afc4c234-9f9d-11e7-9be2-8bb85970f5b1.png)

In my case, I should specify ```bins``` parameter to get a correct result.
```python
       for name, param in resnet18.named_parameters():
            writer.add_histogram(name, param, n_iter, bins='auto')
```

BTW, thank you for your great work!

**Comment by lanpa** [comment]
Be careful, using `bins='auto'` might hang the code. see #1 

Btw, You can use `resnet18 = models.resnet18(True)` to download a trained model and the result should be pretty or train a model and see how parameters moving around.

Glad that you like it!
