### ISSUE TITLE
Comparison with other tensorboard libs

### ISSUE THREAD

**Issue by LinxiFan** [lanpa/tensorboard-pytorch#3]
Hi, sorry for the non-coding question. What's the difference between this library and the other older ones like [Crayon](https://github.com/torrvision/crayon) and [tensorboard_logger](https://github.com/TeamHG-Memex/tensorboard_logger)? `Crayon` looks a bit heavy-weight because it requires docker. `tensorboard_logger` has not been maintained for 9 months. Other than these, are there any functional differences?

**Comment by ethancaballero** [comment]
I think tensorboard_logger can only be used for scalar data, so it can't be used for data with greater than 0 dims such as histograms.

This tensorboard-pytorch repo seems to be best because it retains all of tensorboard's functionality while remaining lightweight.

**Comment by lanpa** [comment]
`tensorboard_logger` only saves scalar values, while `tensorboard-pytorch` saves other data such as image, audio, text, embedding, etc. Another difference is the suffix "-pytorch", `tensorboard-pytorch` let you pass pytorch tensors directly and it will make conversion behind. Compared with `crayon`, this package also supports more data format.

**Comment by LinxiFan** [comment]
@lanpa this is awesome. I'll stick with your library for my research. Thanks for the efforts!
