### ISSUE TITLE
Fix support for Markdown tables

### ISSUE THREAD

**Issue by achaiah** [lanpa/tensorboard-pytorch#30]
Tensorboard supports displaying of Markdown (including tables). However, passing a markdown table into tensorboard-pytorch seems to mangle the table.

**Comment by lanpa** [comment]
I have this issue before. Tensorboard just don't respect some markdown characters. Do you have markdown code that works on TensorFlow?

**Comment by achaiah** [comment]
I believe this works in tensorflow: `'''a|b\n-|-\nc|d'''` and is rendered as a table.

**Comment by achaiah** [comment]
Also, html-like markup doesn't render correctly e.g. `<b>This should be bold</b>` and neither do html tables :(

**Comment by lanpa** [comment]
HI, I Just had a try and I think it needs a big rework on this plugin. Will fix if I have time.

**Comment by sonack** [comment]
@lanpa Does tensorboardX support it now ?  I am really looking forward to it. 🥇

**Comment by lanpa** [comment]
@sonack Yes, please check `demo.py` as shown in https://github.com/lanpa/tensorboardX/commit/83b90b78d33c90ff016959c67ec6b7afedf931b5
