### ISSUE TITLE
Why is the audio sample rate fixed at 44100?

### ISSUE THREAD

**Issue by greaber** [lanpa/tensorboard-pytorch#34]
From glancing at the code, the `audio` function in `summary.py` seems to take a sample rate argument, so it looks like it would be trivial for the `add_audio` method of `SummaryWriter` to take an optional sample rate argument and pass it along to `audio`.  Is there some complicating factor here?

**Comment by lanpa** [comment]
Because I think nobody cares about it. lol

Would you like to send a PR?

**Comment by greaber** [comment]
Sure. I'm planning to switch from crayon to tensorboard-pytorch to be able to log audio, and I will make a pull request to add this feature as part of that.
