### ISSUE TITLE
Support for other scalar data types than the builtin 'float' and 'int'

### ISSUE THREAD

**Issue by tro4els** [lanpa/tensorboard-pytorch#37]
Would it be possible to use numpy.isscalar(x) to condition on data type in x2num.makenp, or is there a good reason not to? It seems to me that this would simplify the code and add support for numpy.floatXX and numpy.intXX.

**Comment by lanpa** [comment]
updated. You can use `pip install git+https://github.com/lanpa/tensorboard-pytorch` to have a test.

**Comment by tro4els** [comment]
Thanks
