### ISSUE TITLE
Text output not working (no graph is present)

### ISSUE THREAD

**Issue by timbmg** [lanpa/tensorboard-pytorch#38]
When I'm trying to log text with tensorboard using this code
```
from tensorboardX import SummaryWriter
w = SummaryWriter("runs/test")
w.add_scalar("s", 1)
w.add_text("t", "text")
```
I get the following error:
```
ERROR:tensorflow:Attempting to process TensorSummary output, but no graph is present, so processing is impossible. All TensorSummary output will be ignored.
Adding scalars for example works.
```
In my tensorboard no "Text" menu item is displayed. 

Logging scalars works fine.

The following versions are installed:
tensorboardX (0.8)
tensorflow (1.3.0)
tensorflow-tensorboard (0.1.7)
torch (0.2.0.post3)

**Comment by lanpa** [comment]
Can't reproduce. How did you invoke the tensorboard command?
=============
tensorboardX (0.8)
tensorflow-tensorboard (0.1.7)
Mac

**Comment by timbmg** [comment]
like this `tensorboard --logdir logs`

**Comment by lanpa** [comment]
should be `tensorboard --logdir runs` if you use `w = SummaryWriter("runs/test")`

**Comment by timbmg** [comment]
Oh yes of course. Unfortunately still the same problem.

**Comment by lanpa** [comment]
can you upload your `runs` folder?
[runs.zip](https://github.com/lanpa/tensorboard-pytorch/files/1344860/runs.zip)

**Comment by timbmg** [comment]
The issue was with my config. Can be closed.
