### ISSUE TITLE
tensorboard-pytorch installation: "No module named tensorflow"

### ISSUE THREAD

**Issue by jtang10** [lanpa/tensorboard-pytorch#39]
Hello there,

I am new to tensorboard-pytorch and submitting issue on GitHub, so if you think asking question instead of filing bugs here is not a good idea, I will ask this somewhere else (please tell me where) and delete this issue. 

I followed the walkthrough on this repo's README and successfully run the tensorboardX. Everything I intend to record has been saved, but there is only one issue when I run tensorboard in terminal. When I run `tensorboard --logdir=logger`, 'No module named tensorflow' prompted from tensorboard/main.py. I have to activate my tensorflow environment and run the command to visualize recorded file.

I have run two commands `pip install tensorboardX` and `pip install tensorflow-tensorboard` successfully by the way. I used python 2.7 virtualenv to integrate everything about pytorch together.

**Comment by jtang10** [comment]
Sorry for this stupid issue. I blindly followed the instructions without realizing tensorflow itself has to be installed as well.

**Comment by lanpa** [comment]
Not your fault, `tensorflow-tensorboard` removed the dependency of `tensorflow` since 0.1.5. Therefore the installation guideline is outdated. Thanks for notification.

**Comment by isalirezag** [comment]
so how should we install tensorbardx?

**Comment by lanpa** [comment]
@isalirezag `pip install tensorboardX` for tensorboardX (the loggor), and `pip install tensorboard` for tensorboard(the web server)
