### ISSUE TITLE
why do you use clone in histogram examples?

### ISSUE THREAD

**Issue by greaber** [lanpa/tensorboard-pytorch#41]
From the readme,

```
for name, param in resnet18.named_parameters():
            writer.add_histogram(name, param.clone().cpu().data.numpy(), n_iter)
```

Could we instead use the following simpler version?

```
for name, param in resnet18.named_parameters():
            writer.add_histogram(name, param.data.cpu().numpy(), n_iter)
```

(Or we could put the .cpu() before the .data probably -- I don't think this matters.)

**Comment by lanpa** [comment]
Instead you can use `writer.add_histogram(name, param, n_iter)` if you use latest tensorboardX (see demo.py). I forget to update readme.
