### ISSUE TITLE
slider bar's values jumps when moving the bar's knob

### ISSUE THREAD

**Issue by ZhengRui** [lanpa/tensorboard-pytorch#44]
I used `add_image()` to record some visualization results at each step/epoch, during training the image at each step/epoch is displayed well, but after the training is done, when i draw the knob left and right, it doesn't increase or decrease incrementally by step 1, instead step numbers can just goes like 1->2->4->6->12 ..., which is annoying, my college also has the same issue. I guess it is a front-end issue, can anyone post a fix? Thanks.

**Comment by lanpa** [comment]
The `Tweaks` section in readme may help.

**Comment by ZhengRui** [comment]
I tried to change "event_accumulator.TENSORS" from 10 to 100, it seems has no effects, is it the right thing that I should modify? As from search of my "/usr/local/lib/python2.7/dist-packages/tensorboard/backend/application.py" file, I only found "event_accumulator" in this setting.

**Comment by lanpa** [comment]
which version of TB are you using? I am on 0.1.7

**Comment by ZhengRui** [comment]
I am on 0.1.8

**Comment by lanpa** [comment]
HI, I just tried 0.1.8 and found that by also modifying `image_metadata` in `tensorboard/backend/application.py` works:

```python

DEFAULT_SIZE_GUIDANCE = {
    event_accumulator.TENSORS: 100,
}

# TODO(@wchargin): Once SQL mode is in play, replace this with an
# alternative that does not privilege first-party plugins.
DEFAULT_TENSOR_SIZE_GUIDANCE = {
    scalar_metadata.PLUGIN_NAME: 1000,
    image_metadata.PLUGIN_NAME: 100,
    audio_metadata.PLUGIN_NAME: 10,
    histogram_metadata.PLUGIN_NAME: 500,
}

**Comment by ZhengRui** [comment]
awesome, that works, thanks, close this issue now.

**Comment by liulai** [comment]
I use the domo.py, but the PROJECTOR is not working.Why?
![微信图片_20191120014746](https://user-images.githubusercontent.com/12567867/69172045-0f3dbd80-0b38-11ea-95a7-36db523c8188.png)
