### ISSUE TITLE
Tags are interpreted as independent runs

### ISSUE THREAD

**Issue by bestxolodec** [lanpa/tensorboard-pytorch#45]
This code 
```
 writer = SummaryWriter(log_dir="runs/first_run") 
 writer.add_scalars('loss/pi', {"policy": pi_loss.data[0], 
                                "value": V_pi_loss.data[0], 
                                "entropy": pi_entropy.data[0]}, i_episode) 

```

yields in tensorboard page 

<img width="344" alt="screen shot 2017-10-28 at 18 59 03" src="https://user-images.githubusercontent.com/3531361/32136216-d642403a-bc12-11e7-8286-61cfb17fac24.png">

I guess, this is not the way the Tensorboard is supposed to recognise tags. 

Also, if I add, for example,  30 different summaries (including a bunch of histograms and scalars), CPU consumption increases significantly (up to the whole available cpu time). Tensorboard becomes almost irresponsible. 
I guess such a behaviour may also be due to very many tags being interpreted by tensorboard as independent runs. 

`tensorboard-pytorch==0.8` was installed with pip
`tensorboard` is of 0.1.8 (more older versions of tensorboard are also susceptible to the same issue).

**Comment by bestxolodec** [comment]
[In Tensorflow the result analogous to `add_scalars()` also needs a separate file_writer](https://github.com/tensorflow/tensorflow/issues/7089#issuecomment-295857875) and thus also will result in additional lines in the `runs` section of tensorboard.

**Comment by lanpa** [comment]
Hi, I think this is a pretty hacky method. To plot many sequences at once, you should dump the data to json format with `export_scalars_to_json()` and plot with other software.

**Comment by bestxolodec** [comment]
Ok, thank you.
