### ISSUE TITLE
The add_graph does not work

### ISSUE THREAD

**Issue by CarryJzzZ** [lanpa/tensorboard-pytorch#46]
Hi! my code is listed below; but the procedure does not work,  it stops there all time. How can i get over it? thx!
# create model
    model = dn.DenseNet3(args.layers, 10, args.growth, reduction=args.reduce,
                         bottleneck=args.bottleneck, dropRate=args.droprate, inputdim=args.inputdim)

    res = model(torch.autograd.Variable(torch.Tensor(1, 3, 32, 32), requires_grad=False))
    writer = SummaryWriter("runs/%s" % (args.name))
    writer.add_graph(model, res)
    writer.close()

**Comment by lanpa** [comment]
What is `DenseNet3`? Any error message?

**Comment by CarryJzzZ** [comment]
DenseNet3 is a class used to create the DenseNet, listed as follows; There are no error message, it just stops here, and does not go to train(cause train the net will print the process), i also opened the tensorboard, found nothing in it. sad....
class DenseNet3(nn.Module):
    def __init__(self, depth=10, num_classes=10, growth_rate=12,
                 reduction=0.5, bottleneck=False, dropRate=0.2, inputdim=24):

**Comment by akurniawan** [comment]
Even the example in https://github.com/lanpa/tensorboard-pytorch/blob/880fbaf6edd85b9e8ed1ab884daf1ed0b836c16c/demo_graph.py doesn't work. The error message was `KeyError: 4646265864`.
I am using tensorflow 1.4.1 and pytorch 0.3. Are they not supported yet?

**Comment by lanpa** [comment]
@akurniawan The current add_graph function only supports pytorch v0.2. For 0.3 please try the onnx version: https://github.com/lanpa/tensorboard-pytorch/blob/master/onnx_graph.py
(you may need to install onnx as well)

**Comment by adamtwig** [comment]
The onnx_graph.py script linked above does not exist for me. 

Could you clarify how to get a working graph visualization using pytorch 0.3?

**Comment by akurniawan** [comment]
@adamtwig I believe this is the correct one https://github.com/lanpa/tensorboard-pytorch/blob/master/demo_graph.py

**Comment by lanpa** [comment]
@adamtwig @akurniawan 
https://github.com/lanpa/tensorboard-pytorch/blob/9a3f9cca7057af515df64fdbfa523dbf16c1211d/onnx_graph.py

The onnx version don't have scope feature. So the graph is not pretty. 
I you know how to build pytorch0.4, I strongly suggest you to use the new graph plotting function.

**Comment by akurniawan** [comment]
@lanpa are you referring to this one? https://github.com/szagoruyko/functional-zoo/blob/master/visualize.py, so far that's the only thing that I can found and it's not official from pytorch. so I don't think pytorch 0.4 is necessary(?)

**Comment by lanpa** [comment]
@akurniawan 

The internal graph representation are slightly different between pytorch 0.2, 0.3, 0.4
So tensorboard-pytorch uses different code to dump the graph.

To be more clear:

In 0.3, the easiest way is first dump the graph from pytorch to onnx, then dump from onnx.
(need to install onnx)
https://github.com/lanpa/tensorboard-pytorch/blob/9a3f9cca7057af515df64fdbfa523dbf16c1211d/onnx_graph.py

In 0.4(master branch), the network can be dumped to tensorboard directly without temporarily exporting to onnx. And I think the best thing is that scope is supported in this version :)
https://github.com/lanpa/tensorboard-pytorch/blob/master/demo_graph.py

Btw, the `visualize.py` should work for v0.2

You can see the result from the newest version:
http://35.197.26.245:6006/
