### ISSUE TITLE
Behavior of `global_step=None`

### ISSUE THREAD

**Issue by LinxiFan** [lanpa/tensorboard-pytorch#49]
This is probably a stupid question: I don't understand the behavior when `global_step=None`. I'd expect the plot's x-axis to correspond to wallclock time, but in reality it squeezes the curve to a single dot. 
Both this repo and the official TB repo say `global_step` is optional. Under what situation do I actually set it to None?

**Comment by lanpa** [comment]
I always pass n_iter explicitly. It's more intuitive.

However you can try this for wall clock time:
```python
import time
for n_iter in range(100):
    s1 = torch.rand(1) # value to keep
    writer.add_scalar('data/scalar1', s1[0]) 
    time.sleep(0.1)
```
Note that it's important to have a `sleep`.

![image](https://user-images.githubusercontent.com/2005323/33197375-ebadc800-d11f-11e7-8418-5d77da2b34bf.png)

**Comment by LinxiFan** [comment]
Yes, I know you can emulate wall clock time that way. However, I do want to understand what does `global_step=None` mean, and why is it even optional at all.

**Comment by lanpa** [comment]
Setting `global_step=None` means no step information is saved in protobuf (while time is still logged). So if users don't want to maintain a global step variable in the code, they can simply ignore this argument.

**Comment by LinxiFan** [comment]
Gotcha. I guess it's always good to make it explicit then. Thanks!
Happy Black Friday. ;)
