### ISSUE TITLE
Save the writer state and restore it for next run

### ISSUE THREAD

**Issue by jyzhang-bjtu** [lanpa/tensorboard-pytorch#50]
Currently, the tensorboard for pytorch can not save the summarywrite state and can not load it for next run.
It would be more convenient to add the save_state and load_state method.

best

**Comment by lanpa** [comment]
Hi, would you provide a usecase about this feature? Why you need to stop training and then resume? Thanks

**Comment by jyzhang-bjtu** [comment]
I use tensorflow and pytorch both. In tensorflow, I can use tf.train.Supervisor to manange running models. The tf.train.supervisor can periodically save the running state (or check point) and summary on the disk. It can also restore the running state and the summary for the logging dir.
Use-case 1:Therefore, for some complicated models, I often divided the training process into multiple number of epochs.  At end of each batch of epochs, I will check the training results to see whether the trained model is good. If it is Ok, I will terminate the training. If not, I will restart the training.
Use-case 2:For some case, electric power-off will terminate my training process. Thus, when I write a computer software, I often add the save_state and load_state in my program.
Because pytorch is simple and lack of framework like tf.train.supervisor, I need to write it by hand.

I hope these two use case will help you.

Best

**Comment by lanpa** [comment]
I found that tensorboard concats data by default, if the event files are in the same directory.

```python
with SummaryWriter('runs/Dec01_19-58-48_Z97X') as w:
    for i in range(100):
        w.add_scalar('test', np.random.randn(), i)

import time
time.sleep(1)

with SummaryWriter('runs/Dec01_19-58-48_Z97X') as w:
    for i in range(100):
        w.add_scalar('test', np.random.randn()+3, i+100)
```
As long as programmer knows the dir name (and `global_iteration`), the second usecase can be fulfilled.

For case 1, do you mean something like rollback the history? (discard the bad training result) If I am correct, I guess that delete the event file manually do the trick.

**Comment by jyzhang-bjtu** [comment]
Got it. Today, I read the source code of tensorboard again. I found the same thing as you found. 
Thanks a lot.
