### ISSUE TITLE
add_histgram : TypeError

### ISSUE THREAD

**Issue by jyzhang-bjtu** [lanpa/tensorboard-pytorch#51]
The code is add_histogram(name,data, niter) as examples.
But it can not work.
The error msg is 
  File "/opt/pytorch/lib/python3.5/site-packages/tensorboardX/writer.py", line 305, in add_histogram
    self.file_writer.add_summary(histogram(tag, values, bins), global_step)
  File "/opt/pytorch/lib/python3.5/site-packages/tensorboardX/summary.py", line 113, in histogram
    hist = make_histogram(values.astype(float), bins)
  File "/opt/pytorch/lib/python3.5/site-packages/tensorboardX/summary.py", line 131, in make_histogram
    bucket=counts)
TypeError: 0 has type numpy.int64, but expected one of: int, long, float

**Comment by lanpa** [comment]
I could not locate the corresponding code in your error message in newest (the version on github) tensorboardX . Which version are you on?

**Comment by jyzhang-bjtu** [comment]
I use pip3 install tensorboardX, which version is 0.8. I will update it later.

**Comment by lanpa** [comment]
The pip version is pretty old. XD
Please try `pip install git+https://github.com/lanpa/tensorboard-pytorch` if you have time~

**Comment by jyzhang-bjtu** [comment]
I upgrade the version from 0.8 to 0.9. But the problem still exist.

**Comment by lanpa** [comment]
So what is the error message in V0.9?

**Comment by jyzhang-bjtu** [comment]
same as V0.8. Given as follows, where fun_wr is my wrapper class to write summary.
  File "/tchelpers.py", line 346, in write
    fun_wr(mn0,data[mn0], niter)    
  File "/opt/pytorch/lib/python3.5/site-packages/tensorboardX/writer.py", line 323, in add_histogram
    self.file_writer.add_summary(histogram(tag, values, bins), global_step)
  File "/opt/pytorch/lib/python3.5/site-packages/tensorboardX/summary.py", line 114, in histogram
    hist = make_histogram(values.astype(float), bins)
  File "/opt/pytorch/lib/python3.5/site-packages/tensorboardX/summary.py", line 132, in make_histogram
    bucket=counts)
TypeError: 0 has type numpy.int64, but expected one of: int, long, float

**Comment by jyzhang-bjtu** [comment]
I will try to debug it later if my training machine is free...

**Comment by lanpa** [comment]
Hi, what is the output of  `(type(mn0)`, `type(data[mn0])`.

**Comment by jyzhang-bjtu** [comment]
I will provide sample data to you later because my machine is not free...

**Comment by jyzhang-bjtu** [comment]
The attached is my data (numpy *.npz file in zip file) to be used in the function "make_histogram" in the summary.py.

The error arises in the last para of "HistogramProto" function, which is bucket=counts.

I hope this will help you to debug the program.

[data.zip](https://github.com/lanpa/tensorboard-pytorch/files/1547124/data.zip)

**Comment by lanpa** [comment]
no error on my machine :(

```python
import numpy as np
from tensorboardX import SummaryWriter

data = np.load('test.npz')
bins = data['bins']
data = data['values']
print(data.shape)
with SummaryWriter() as w:
    w.add_histogram('data', data, 0, bins=bins)
    w.add_histogram('data', data, 1)
    
```

**Comment by jyzhang-bjtu** [comment]
I use the code above but the error is still there. The error msg is same as the before.
Is this due to the version of numpy? My numpy version is 1.13.0.

**Comment by jyzhang-bjtu** [comment]
I debug it again and again. I found that error arose in 
HistogramProto(min=values.min(),max=values.max(), num=len(values),sum=values.sum(),sum_squares=sum_sq,bucket_limit=limits,bucket=counts). 

because the type of counts is np.int64 array where is given by     

counts, limits = np.histogram(values, bins=bins) in summary.py.

If I replace counts with a list, such as [1,2], everything is ok.

**Comment by lanpa** [comment]
Hi, my `counts.dtype` is also `numpy.int64`. Based on your description, it looks like the protobuf does not convert `ndarray` to the datatype it expect. Btw, have you run `demo.py` before? Did it break the code? Thanks

**Comment by jyzhang-bjtu** [comment]
If use demo.py, got the same error as follows

Traceback (most recent call last):
  File "demo.py", line 35, in <module>
    writer.add_histogram(name, param, n_iter)
  File "/opt/pytorch/lib/python3.5/site-packages/tensorboardX/writer.py", line 323, in add_histogram
    self.file_writer.add_summary(histogram(tag, values, bins), global_step)
  File "/opt/pytorch/lib/python3.5/site-packages/tensorboardX/summary.py", line 114, in histogram
    hist = make_histogram(values.astype(float), bins)
  File "/opt/pytorch/lib/python3.5/site-packages/tensorboardX/summary.py", line 132, in make_histogram
    bucket=counts)
TypeError: 0 has type numpy.int64, but expected one of: int, long, float
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f6f077a5378>
Traceback (most recent call last):
  File "/opt/pytorch/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable

**Comment by jyzhang-bjtu** [comment]
If I upgrade the protobuf from 3.0.0 (in debian distribution) to the latest version (3.5.0), everything is ok.

**Comment by lanpa** [comment]
I reproduced it on a VM and I found that the minimum working version is 3.2.0. Thanks!
