### ISSUE TITLE
'SummaryWriter' object has no attribute 'add_scalars'

### ISSUE THREAD

**Issue by yalaudah** [lanpa/tensorboard-pytorch#53]
Hi, 

I'm using version 0.6, and it works fine when I use `writer.add_scalar`. However, using `writer.add_scalars` returns the following error: 

```
writer.add_scalars('loss',{'train_loss':loss.data[0],

AttributeError: 'SummaryWriter' object has no attribute 'add_scalars'
```

Is there any explanation why this fails?

**Comment by lanpa** [comment]
Your version is too old. We are on 0.9 now.

**Comment by manufonn** [comment]
check spelling
