### ISSUE TITLE
Error when running on Windows 10 with VS2017

### ISSUE THREAD

**Issue by LowBoonKeong** [lanpa/tensorboard-pytorch#55]
Hi, I meet the following error when running on Windows 10 Command Prompt and x64 Native Tools Command Prompt for VS2017. I followed the pytorch faster-rcnn to perform visualization on the trained model. https://github.com/ruotianluo/pytorch-faster-rcnn 
![error](https://user-images.githubusercontent.com/30174905/33730928-814ee294-dbbc-11e7-826c-b0f9541ae140.PNG)

I hope to get some information to perform visualization on Windows 10. 
Thank you.

**Comment by lanpa** [comment]
Did you forget to escape `\`?

**Comment by LowBoonKeong** [comment]
Hi @lanpa, thanks for your reply. There is still an error after I added in the escape character and run it on Windows command prompt and x64 Native Tools Command Prompt for VS2017. 
![error](https://user-images.githubusercontent.com/30174905/33748880-ec768fd8-dc05-11e7-9a0f-9d5ed2af7d58.PNG)

**Comment by lanpa** [comment]
I meant `tensorboard\\vgg16\\icdar_train`, double backslash

**Comment by LowBoonKeong** [comment]
Hi, @lanpa there is still the same error. 
![error](https://user-images.githubusercontent.com/30174905/33749826-03cb1988-dc0b-11e7-9c1a-cfdd6c1e3e81.PNG)

**Comment by lanpa** [comment]
oops, are you in ipython? The command should be run in system prompt

**Comment by LowBoonKeong** [comment]
Hi @lanpa , the problem solved when running in system problem. Really appreciate and thanks for your help very much. Great.
