### ISSUE TITLE
Cat issue in add_embedding with cuda tensor

### ISSUE THREAD

**Issue by apsdehal** [lanpa/tensorboard-pytorch#58]
In line number: https://github.com/lanpa/tensorboard-pytorch/blob/master/tensorboardX/embedding.py#L20

If a cuda tensor is passed it will throw an error as torch.randn will generate a cpu tensor and thus both won't be same type. Either throw an explicit warning or check for type of `label_img` and convert rand tensor accordingly. 

I solved it by converting passed tensor to cpu for now.

**Comment by lanpa** [comment]
Thanks, this reminds me that the 'dirty fix' in `make_sprite` can be removed :)
Please leave this issue opened. So I wont forget it.
