### ISSUE TITLE
Graph visualization clarification

### ISSUE THREAD

**Issue by bhchiang** [lanpa/tensorboard-pytorch#59]
I generated a graph are there a few operations that are unclear to me since I did not explicitly call them in PyTorch.

TransposeBackward - is this included with all nn.Linear operations?
AddmmBackward - is the short for add, matrix multiply for nn.Linear operations?

Below is a snippet of my graph.
![screen shot 2017-12-24 at 7 54 43 pm](https://user-images.githubusercontent.com/10623745/34332328-51ba439a-e8e4-11e7-83cc-45442db0a654.png)

**Comment by lanpa** [comment]
Yes. A linear kernel is f(x) = X * W^T + b
Here `Backward` is pytorch's internal representation. You can ignore it.

more information on addmm:
http://pytorch.org/docs/master/torch.html#torch.addmm

**Comment by bhchiang** [comment]
Thanks!
