### ISSUE TITLE
Sdist to PyPI

### ISSUE THREAD

**Issue by Breakend** [lanpa/tensorboard-pytorch#64]
Hi,

Is it possible to upload the latest sdist to python such that there is a tar.gz and whl like in Keras?  It would be nice to have a non-binary import from PyPI.

Link to keras example: https://pypi.python.org/pypi/Keras

Thanks!

**Comment by lanpa** [comment]
HI, There is no binary file contained in current `whl` file. The only thing need to be compiled is *.proto, and the output is also python code.  Is there any reason to use non-binary import?
