### ISSUE TITLE
How to use the function add_graph(model, input_to_model, verbose=False)? (It seems that demo_graph.py is not executable)

### ISSUE THREAD

**Issue by MrStrangerYang** [lanpa/tensorboard-pytorch#66]
At the beginning, I tried to run demo_graph.py, but the result was always 
![27 w 0t0pud3z riz p8r](https://user-images.githubusercontent.com/15873712/34677784-2561f772-f4cc-11e7-985d-5ba3db1f596c.png)
Then I tried to add a main function code:
```
if __name__ == '__main__':
    exp_name = 'model_' + time.strftime("%y-%m-%d_%H-%M-%S", time.localtime()) + 'resnet'
    w = SummaryWriter('./run' + '/' + exp_name)

    dummy_input = Variable(torch.rand(1, 3, 224, 224))
    model = torchvision.models.resnet18()
    w.add_graph(model, dummy_input)
```
And started up the tensorboard using the command:
```
tensorboard --logdir ./run --port 6611
```
However the result showed in my browser was 
![73r9x ym3d u8 4q pl9npb](https://user-images.githubusercontent.com/15873712/34678099-0ff34a3e-f4cd-11e7-936d-c94057acc037.png)

So, I wonder to know the correct way to use the  function add_graph to draw the network structure diagram like this:
![uy5 4yg16 m bhg 9 aw](https://user-images.githubusercontent.com/15873712/34678147-354ce984-f4cd-11e7-9d92-e15a879bbee0.png)

**Comment by lanpa** [comment]
This screenshot is very old.(for pytorch 0.2)

please check #46 for more information. I suggest to use `add_graph()` along with pytorch 0.4 for best view. (And help me verifying the result lol)

**Comment by JiamingSuen** [comment]
I figured out that tensorboardX must be installed from source in order to use `add_graph()`, with pytorch > 0.4. Maybe this should be put into readme as well.

**Comment by lanpa** [comment]
@JiamingSuen Thanks, I think it should be mentioned. And FYI, the pip package was updated yesterday.

**Comment by Anubhav7** [comment]
@JiamingSuen Thanks for pointing out that this was due to version mismatch. Works after upgrading pytorch to 0.4
