### ISSUE TITLE
Histogram tab does not work

### ISSUE THREAD

**Issue by smolendawid** [lanpa/tensorboard-pytorch#73]
My histogram tab looks like this, after running demo.py

<img width="916" alt="screen shot 2018-01-29 at 8 30 25 am" src="https://user-images.githubusercontent.com/9264154/35498519-f77cf40c-04ce-11e8-8979-08fd797c0a7d.png">

I suspect, that it's not a proper shape. When I use my custom models and training, histograms look the same (some seem to have smaller amplitude while training, but not clearly). 

I am using pip version (1.0) of TensorBoardX, TensorBoard 0.4.0rc3, PyTorch 0.3.0.post4

**Comment by lanpa** [comment]
hi, have you tried #42 and #56?

**Comment by smolendawid** [comment]
I' pretty sure I was searching for the "histogram" word in issues, so I don't know how could I miss it.

Thanks, changing _bins_ value helped. I set _bins='doane'_

**Comment by lanpa** [comment]
Github defaults to search issues that still unsolved, maybe you missed that.
