### ISSUE TITLE
KeyError: '2' when executing add_graph()

### ISSUE THREAD

**Issue by KaiWU17TUM** [lanpa/tensorboard-pytorch#75]
Hi, I've just installed pytorch 0.4 and the demo_graph.py works normally.
When I try to use this add_graph function for my own model, the following error exists.
<img width="570" alt="1" src="https://user-images.githubusercontent.com/33467082/35758622-45503d98-0875-11e8-9982-e660d6b22748.png">
<img width="335" alt="2" src="https://user-images.githubusercontent.com/33467082/35758625-47f27700-0875-11e8-9983-50b16c539e0b.png">

Thanks for your time

**Comment by lanpa** [comment]
Hi, can you show the output of `w.add_graph(actor, (dummy_input,), verbose=True)` ?

I guess some operators are not supported for tracing yet.

**Comment by lanpa** [comment]
https://github.com/pytorch/pytorch/issues/5101
