### ISSUE TITLE
Histogram displays wrong (different with distribution)

### ISSUE THREAD

**Issue by fengziyue** [lanpa/tensorboard-pytorch#76]
@lanpa 
I add this two line to demo.py:

`x_rand=torch.rand(64)
writer.add_histogram('rand',** x_rand+n_iter, n_iter)`

tensorboardx displays this in "Distribution":
![screenshot from 2018-02-03 19-21-19](https://user-images.githubusercontent.com/21237230/35766733-7077fb2a-0918-11e8-8723-ce4bcba63836.png)
and this in "Histogram":
![screenshot from 2018-02-03 19-21-46](https://user-images.githubusercontent.com/21237230/35766734-871e2552-0918-11e8-97d4-ba2ea7e2b93b.png)

the mean value of x_rand has changed but Histogram shows it doesn't

ubuntu 16.04
python 2.7
pytorch 0.3
tensorflow1.4.0

**Comment by fengziyue** [comment]
@lanpa

**Comment by lanpa** [comment]
hi. I just wrote a wiki yesterday. It should help.

https://github.com/lanpa/tensorboard-pytorch/wiki

**Comment by fengziyue** [comment]
Thank you!
I set the bins in add_histogram to 'doane' and solved the problem.
