### ISSUE TITLE
Supporting intensity-only images

### ISSUE THREAD

**Issue by AndreiBarsan** [lanpa/tensorboard-pytorch#77]
Tensorboard should have no problem displaying single-channel images.
However, there's a piece of code inside tensorboard-pytorch which assumes the shape of any logged tensor image should have three components, line 165 in `summary.py`: 

```python
    height, width, channel = tensor.shape
```

However, because of how PIL is designed, image shapes should have two components, not three, for intensity images. See the source code of `PIL.fromarray`, namely, the `_fromarray_typemap`, which assumes L-only images do not have a (single-element) third dimension.

However, such images cannot get to PIL because of the `tensor.shape` unpacking in `tensorboard-pytorch`, which fails of the given tensor is only 2D.

I guess this is just an incompatibility between how PIL and TensorBoard think of channels (TB seems to want single-channel images to be shaped (W, H, 1), whereas PIL (W, H)).

The workaround for grayscale images is to simply do something like `img = np.transpose(np.stack((img, img, img)), (1, 2, 0))`, but this feels a bit hacky.

What are your thoughts? Should this be fixed within `tensorboard-pytorch`, or is this more of a PIL/tensorboard issue?

Thank you for working on this! `tensorboard-pytorch` has been an incredibly useful package when working with PyTorch!

**Comment by lanpa** [comment]
Hi, 2D image should be handled implicitly. 
https://github.com/lanpa/tensorboard-pytorch/blob/master/tensorboardX/x2num.py#L77

Can you post the error message?

**Comment by iacopomasi** [comment]
Does tenosorboardX support grayscale images? Look at [this](https://tensorboardx.readthedocs.io/en/latest/tensorboard.html#tensorboardX.SummaryWriter.add_image), it does not seem so.

**Comment by lanpa** [comment]
@iacopomasi Setting `dataformats='HW'` should do the trick.

**Comment by iacopomasi** [comment]
OK, thanks. For now I just concat the grayscale image 3 times to simulate a RGB but thanks for answering!
