### ISSUE TITLE
Histogram is not working?

### ISSUE THREAD

**Issue by juliohm** [lanpa/tensorboard-pytorch#78]
Hi, thanks for this project, it is very helpful and welcome!

I wonder if the histogram tab in TensorBoard is working? I just tried the default MNIST example from the PyTorch documentation, and that is how it looks like:

![screenshot from 2018-02-05 21-56-25](https://user-images.githubusercontent.com/3345261/35843907-a3d20c10-0abf-11e8-975e-45d0e352379f.png)

I tried with my own model and had the same issue. The Distributions tab looks reasonable:

![screenshot from 2018-02-05 21-58-36](https://user-images.githubusercontent.com/3345261/35843932-bd5ebe80-0abf-11e8-80a8-66aad177b4d9.png)

Could you please confirm this is a bug?

**Comment by lanpa** [comment]
does https://github.com/lanpa/tensorboard-pytorch/wiki work?

**Comment by juliohm** [comment]
Yay! Passing the option `bins='doane'` to `add_histogram` solves the issue, big thanks!
