### ISSUE TITLE
How to show the latest 3 images in the tensorboard-pytorch?

### ISSUE THREAD

**Issue by Jiankai-Sun** [lanpa/tensorboard-pytorch#82]
From the README.md, I find that I can add image into the tensorboard via
```
writer.add_image('Image', x, n_iter)
```

However, the parameters used in the original tensorboard are:
```
tf.summary.image('input', image_shaped_input, 10)
```
```
image(
    name,
    tensor,
    max_outputs=3,
    collections=None,
    family=None
)
```
max_output: Max number of batch elements to generate images for.
My question is: How can we add serveral images to the tensorboard consecutively? How to show the latest 3 images in the tensorboard-pytorch?

**Comment by lanpa** [comment]
tensorboardX saves your image whenever you called `writer.add_image('Image', x, n_iter)`. To show the latest 3 images, you can cache last three images during training and write them at once outside the training loop.

**Comment by Jiankai-Sun** [comment]
Thank you for your reply! Could you please provide an example code about how to " cache last three images during training and write them at once outside the training loop". I wonder how to set `x` if I write several images at once.

Futhermore, once I call  `writer.add_image('Image', x, n_iter)`, could I find the images which is written previously?

**Comment by lanpa** [comment]
```python
from collections import deque
q = deque([],3)
while True: #training loop
  img = model(x)
  q.appendleft(img)

for img in q:
  save_image()...
```

I think what you need is torchvision's `save_image()` currently. I can write a short script to dump tensorboard images this holiday.

**Comment by lanpa** [comment]
https://github.com/lanpa/tensorboard-dumper
