### ISSUE TITLE
UnicodeDecodeError in add_graph

### ISSUE THREAD

**Issue by shahabty** [lanpa/tensorboard-pytorch#90]
Hello,
I'm trying to visualize my network by add_graph module
However, I faced this error:

, line 65, in graph
attr={'lanpa': AttrValue(s=node['attr'].encode(encoding='utf_8'))}))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 21: ordinal not in range(128)

Thanks,

**Comment by lanpa** [comment]
Hi, does `demo_graph.py` have same error on your environment?
