### ISSUE TITLE
Issue with add_text

### ISSUE THREAD

**Issue by evcu** [lanpa/tensorboard-pytorch#91]
Hi, 

For some reason I am not able to add_text. When I dod add_text('test','test',1) and then export the json it doesn't appear in the file? Is it normal? I have following tensorflow/tensorboard packages.

tables (3.4.2)
tensorboard (1.6.0)
tensorboardX (1.1)
tensorflow (1.5.0)
tensorflow-tensorboard (1.5.1)
termcolor (1.1.0)

Best

**Comment by lanpa** [comment]
How do you `export the json`? I don't have such button in the web interface.

**Comment by evcu** [comment]
`writer.export_scalars_to_json`. O I see it is only the scalars. For some reason I don't see the text in the tensorboard; how can I verify that it is written probarly. I am trying to debug why I don't see the text in tensorboard.

**Comment by evcu** [comment]
upgraded tensorflow/tensorboard and solved; thanks
