### ISSUE TITLE
Tensorflow 1.6

### ISSUE THREAD

**Issue by evcu** [lanpa/tensorboard-pytorch#92]
With new tensorflow(1.6) it looks like the histogram values that I recorded acts weird. 
1.5
![image](https://user-images.githubusercontent.com/8350242/36916869-28670e50-1e23-11e8-99fa-5c792464363f.png)
1.6
![image](https://user-images.githubusercontent.com/8350242/36916839-10f6b11c-1e23-11e8-8202-4c6f730fb08e.png)

**Comment by lanpa** [comment]
Does https://github.com/lanpa/tensorboard-pytorch/wiki work?

**Comment by evcu** [comment]
of course; didn't know about the wiki before
