### ISSUE TITLE
Looping scalar depending on write order

### ISSUE THREAD

**Issue by fiorenza2** [lanpa/tensorboard-pytorch#93]
Hi, when I run experiments with multiple scalar writes, I get the following behaviour:

<img width="737" alt="weird_loop" src="https://user-images.githubusercontent.com/15997485/36937366-fdd885e6-1f09-11e8-82bd-f5516a71d7bf.png">

Basically if I write a scalar 'a' to the file first (i.e. .add_scalar(a,..) appears first in the code), then the graphs don't exhibit the looping behaviour. However all subsequent scalars will loop over when I start a new run; I'm running tensorboard 1.5.1

**Comment by lanpa** [comment]
How do you start a new run? Did you pass any parameter into `summarywriter()`? If so, you have to use different experiment name for each run or simply leave it empty.

**Comment by fiorenza2** [comment]
Understood, so I was passing the same directory each time, assuming that each run would be written into a different summary. Reverting to the default settings where summaries are stored in './runs' resolves this somewhat. Is there a way for this behaviour on a specified folder apart from incrementing the name each time?

**Comment by lanpa** [comment]
Sorry I cant understand, would you give a example? (such as expected folder structure)
