### ISSUE TITLE
RuntimeError "output padding is not supported" when use add_graph()

### ISSUE THREAD

**Issue by vicmax** [lanpa/tensorboard-pytorch#95]
When I use `writer.add_graph()` to visualize my model, I got this error message. In fact, I did use `output_padding=xx` when I built my CNN model with `nn.ConvTranspose2d`. 

It seems like there is something wrong when we try to visualize a graph which contains `output_padding=xxx` ?

`Traceback (most recent call last):`
`  File "train.py", line 121, in <module>
    writer.add_graph(model, input_v )`

`  File "/home/xxx/.conda/envs/py36/lib/python3.6/site-packages/tensorboardX-1.1-py3.6.egg/tensorboardX/writer.py", line 400, in add_graph
    self.file_writer.add_graph(graph(model, input_to_model, verbose))`

`  File "/home/xxx/.conda/envs/py36/lib/python3.6/site-packages/tensorboardX-1.1-py3.6.egg/tensorboardX/graph.py", line 56, in graph
    torch.onnx._optimize_trace(trace)`

`  File "/home/xxx/.conda/envs/py36/lib/python3.6/site-packages/torch/onnx/__init__.py", line 81, in _optimize_trace
    torch._C._jit_pass_onnx(trace)`

`RuntimeError: torch/csrc/autograd/functions/onnx/convolution.cpp:61: symbolic: output padding is not supported.`

**Comment by lanpa** [comment]
Looks like an onnx issue. Which version of pytorch are you using?

**Comment by lanpa** [comment]
Hi, I tested it `0.3.1` and got the same message as yours. Test with `0.4.0a0+fe810ed` and everything works fine.

**Comment by vicmax** [comment]
@lanpa Thanks for your reply. 
I tested `add_graph()` with a "output_padding" on `torch==0.4.0a0+1ab248d`, and got a new error just like [issue #99 ](https://github.com/lanpa/tensorboard-pytorch/issues/99) . After following the instruction in [PR#106](https://github.com/lanpa/tensorboard-pytorch/pull/106), I had got the right graph.

What's more, what's the possible reason for  'RuntimeError: torch/csrc/autograd/functions/onnx/convolution.cpp:61: symbolic: output padding is not supported.' ?  And will it be fixed in the future version of pytorch(>=0.4.0)
