### ISSUE TITLE
Work well on linux, but window has some problem in add_embedding.

### ISSUE THREAD

**Issue by TaoStarlit** [lanpa/tensorboard-pytorch#96]
Hi, this tensorboard is very useful for my project. But when I using it in Windows, the demo.py can run and generate run folder just like one in Linux.
Then I use tensorboard, they are mostly well, except the embedding, which is the PROJECTOR in the browser.  In the PROJECTOR tag, I can not see any 2D or 3D embedding, while in the command prompt window, there is an unknown when open the "runs/0000 ensor.tsv file" .

**Comment by lanpa** [comment]
Hi, which version of tensorboard are you using?

**Comment by lanpa** [comment]
Should be fixed in 29c6194. Please reopen if needed.
