### ISSUE TITLE
About RNN

### ISSUE THREAD

**Issue by VeritasXu** [lanpa/tensorboard-pytorch#97]
I wrote a RNN program that i did't use nn.model so that I could see the structure. But I find some problem. Code and the datasets are as follow

https://github.com/VeritasXu/RNN

Can you run and see the structure? I think my program is correct, but the input type of add_graph function results in the strange structure. Could you help me ?

**Comment by lanpa** [comment]
I am not familiar with RNN. Maybe you can use some sequential layers to group your modules?

My result:
![image](https://user-images.githubusercontent.com/2005323/37256445-c3caae82-2595-11e8-8e48-168fb6c0ad9b.png)

**Comment by VeritasXu** [comment]
Thank you for your suggestion.  I updated my program two days ago and I think it's the right model. The program you run is what I improved.
tensorboardX is great!
